const words = [
    {"kanji": "会う", "japanese": "あう",  "romaji": "au", "english": "to meet"},
    {"kanji": "青い", "japanese": " あおい",  "romaji": "aoi", "english": "blue"},
    {"kanji": "赤い", "japanese": "あかい",  "romaji": "akai", "english": "red"},
    {"kanji": " 明るい", "japanese": "あかるい",  "romaji": "akarui", "english": "light, bright"},
    {"kanji": "秋", "japanese": "あき",  "romaji": "aki", "english": "autumn, fall"},
    {"kanji": "開く", "japanese": "あく",  "romaji": "aku", "english": "open"},
    {"kanji": "開ける", "japanese": "あける",  "romaji": "akeru", "english": "to open"},
    {"japanese": "あげる",  "romaji": "ageru", "english": "to give"},
    {"kanji": "朝", "japanese": "あさ",  "romaji": "asa", "english": "morning"},
    {"kanji": "朝ご飯", "japanese": "あさごはん",  "romaji": "asagohan", "english": "breakfast"},
    {"kanji": "あさって", "japanese": "あさって",  "romaji": "asatte", "english": "the day after tomorrow"},
    {"kanji": " 足", "japanese": "あし",  "romaji": "ashi", "english": "leg, foot"},
    {"kanji": "明日", "japanese": "あした",  "romaji": "ashita", "english": "tomorrow"},
    {"kanji": "あそこ", "japanese": "あそこ",  "romaji": "asoko", "english": "over there"},
    {"kanji": "遊ぶ", "japanese": "あそぶ",  "romaji": "asobu", "english": "to play"},
    {"kanji": "温かい", "japanese": "あたたかい",  "romaji": "atatakai", "english": "warm"},
    {"kanji": "頭", "japanese": "あたま",  "romaji": "atama", "english": "head"},
    {"kanji": " 新しい", "japanese": "あたらしい",  "romaji": "atarashii", "english": "new"},
    {"kanji": " あちら", "japanese": "あちら",  "romaji": "achira", "english": "over there (polite)"},
    {"kanji": "暑い", "japanese": "あつい",  "romaji": "atsui", "english": "hot (air)"},
    {"kanji": "厚い", "japanese": "あつい",  "romaji": "atsui", "english": "thick"},
    {"kanji": "後", "japanese": "あと",  "romaji": "ato", "english": "later, after"},
    {"kanji": " 貴方", "japanese": "あなた",  "romaji": "anata", "english": "you"},
    {"kanji": "兄", "japanese": "あに",  "romaji": "ani", "english": "older brother"},
    {"kanji": "姉", "japanese": "あね",  "romaji": "ane", "english": "older sister"},
    {"kanji": "あの", "japanese": "あの",  "romaji": "ano", "english": "that (over there)"},
    {"kanji": "あの", "japanese": "あの",  "romaji": "ano", "english": "well, then"},
    {"kanji": "アパート", "japanese": "アパート",  "romaji": "apaato", "english": "apartment"},
    {"kanji": " 浴びる", "japanese": "あびる",  "romaji": "abiru", "english": "to take a shower"},
    {"kanji": "危ない", "japanese": "あぶない",  "romaji": "abunai", "english": "dangerous"},
    {"kanji": "甘い", "japanese": "あまい",  "romaji": "amai", "english": "sweet"},
    {"kanji": "あまり", "japanese": "あまり",  "romaji": "amari", "english": "not so"},
    {"kanji": " 雨", "japanese": "あめ",  "romaji": "ame", "english": "rain"},
    {"kanji": " 洗う", "japanese": "あらう",  "romaji": "arau", "english": "to wash"},
    {"kanji": " 有る", "japanese": "ある",  "romaji": "aru", "english": "to be, to exist"},
    {"kanji": "ある", "japanese": "ある",  "romaji": "aru", "english": "to possess"},
    {"kanji": "歩く", "japanese": "あるく",  "romaji": "aruku", "english": "to walk"},
    {"kanji": "あれ", "japanese": "あれ",  "romaji": "are", "english": "that one"},
    {"kanji": " 良い", "japanese": "いい / よい",  "romaji": "ii, yoi", "english": "good"},
    {"kanji": "いいえ", "japanese": "いいえ",  "romaji": "iie", "english": "no"},
    {"kanji": " 言う", "japanese": "いう",  "romaji": "iu", "english": "to say, to tell"},
    {"kanji": "家", "japanese": "いえ",  "romaji": "ie", "english": "house, home"},
    {"kanji": "行く", "japanese": "いく",  "romaji": "iku", "english": "to go"},
    {"kanji": " いくつ", "japanese": "いくつ",  "romaji": "ikutsu", "english": "how many, how old"},
    {"kanji": "いくら", "japanese": "いくら",  "romaji": "ikura", "english": "how much"},
    {"kanji": "池", "japanese": "いけ",  "romaji": "ike", "english": "pond"},
    {"kanji": "医者", "japanese": "いしゃ",  "romaji": "isha", "english": "doctor"},
    {"kanji": "椅子", "japanese": "いす",  "romaji": "isu", "english": "chair"},
    {"kanji": "忙しい", "japanese": "いそがしい",  "romaji": "isogashii", "english": "to be busy"},
    {"kanji": "痛い", "japanese": "いたい",  "romaji": "itai", "english": "to be painful"},
    {"kanji": "一", "japanese": "いち",  "romaji": "ichi", "english": "one"},
    {"kanji": " 一日", "japanese": "いちにち",  "romaji": "ichinichi", "english": "one day"},
    {"kanji": "一番", "japanese": "いちばん",  "romaji": "ichiban", "english": "No. 1, the best, the first"},
    {"kanji": "いつ", "japanese": "いつ",  "romaji": "itsu", "english": "when"},
    {"kanji": "五日", "japanese": "いつか",  "romaji": "itsuka", "english": "the 5th day of the month, 5 days"},
    {"kanji": " 一緒", "japanese": "いっしょ",  "romaji": "issho", "english": "together"},
    {"kanji": "五つ", "japanese": "いつつ",  "romaji": "itsutsu", "english": "five"},
    {"kanji": "いつも", "japanese": "いつも",  "romaji": "itsumo", "english": "always"},
    {"kanji": "今", "japanese": "いま",  "romaji": "ima", "english": "now"},
    {"kanji": "意味", "japanese": "いみ",  "romaji": "imi", "english": "meaning"},
    {"kanji": " 妹", "japanese": "いもうと",  "romaji": "imouto", "english": "someone’s younger sister"},
    {"kanji": "いや", "japanese": "いや",  "romaji": "iya", "english": "not likable, unpleasant"},
    {"kanji": " 入口", "japanese": "いりぐち",  "romaji": "iriguchi", "english": "entrance"},
    {"japanese": "いる",  "romaji": "iru", "english": "need, must have, be required"},
    {"japanese": "いる",  "romaji": "iru", "english": "to exist"},
    {"kanji": "入れる", "japanese": "いれる",  "romaji": "ireru", "english": "to insert, to put in"},
    {"kanji": "色", "japanese": "いろ",  "romaji": "iro", "english": "color"},
    {"kanji": "色々", "japanese": "いろいろ",  "romaji": "iroiro", "english": "various"},
    {"kanji": " 上", "japanese": "うえ",  "romaji": "ue", "english": "top, on, above"},
    {"kanji": "後ろ", "japanese": "うしろ",  "romaji": "ushiro", "english": "back, rear, behind"},
    {"kanji": "薄い", "japanese": "うすい",  "romaji": "usui", "english": "thin"},
    {"kanji": "歌", "japanese": "うた",  "romaji": "uta", "english": "song"},
    {"kanji": "歌う", "japanese": "うたう",  "romaji": "utau", "english": "to sing"},
    {"kanji": "内", "japanese": "うち",  "romaji": "uchi", "english": "home"},
    {"kanji": " 生まれる", "japanese": "うまれる",  "romaji": "umareru", "english": "to be born"},
    {"kanji": "海", "japanese": "うみ",  "romaji": "umi", "english": "sea"},
    {"kanji": "売る", "japanese": "うる",  "romaji": "uru", "english": "to sell"},
    {"kanji": "上着", "japanese": "うわぎ",  "romaji": "uwagi", "english": "coat, jacket"},
    {"kanji": "絵", "japanese": "え",  "romaji": "e", "english": "picture"},
    {"kanji": "映画", "japanese": "えいが",  "romaji": "eiga", "english": "movie"},
    {"kanji": "映画館", "japanese": "えいがかん",  "romaji": "eigakan", "english": "cinema"},
    {"kanji": "英語", "japanese": "えいご",  "romaji": "eigo", "english": "English language"},
    {"kanji": " ええ", "japanese": "ええ",  "romaji": "ee", "english": "Yes, I see"},
    {"kanji": "駅", "japanese": "えき",  "romaji": "eki", "english": "station"},
    {"kanji": "エレベータ", "japanese": "エレベータ",  "romaji": "erebeeta", "english": "elevator"},
    {"kanji": "円", "japanese": "えん",  "romaji": "en", "english": "Yen"},
    {"kanji": " 鉛筆", "japanese": "えんぴつ",  "romaji": "enpitsu", "english": "pencil"},
    {"kanji": " 御", "japanese": "お",  "romaji": "o", "english": "honorific prefix"},
    {"kanji": "美味しい", "japanese": "おいしい",  "romaji": "oishii", "english": "tasty, delicious"},
    {"kanji": " 大きい", "japanese": "おおきい",  "romaji": "ookii", "english": "big"},
    {"japanese": "おおぜい",  "romaji": " oozei", "english": "many people"},
    {"kanji": " お母さん", "japanese": "おかあさん",  "romaji": "okaasan", "english": "my own mother"},
    {"kanji": "お菓子", "japanese": "おかし",  "romaji": "okashi", "english": "confectionary, cake"},
    {"kanji": " お金", "japanese": "おかね",  "romaji": "okane", "english": "money"},
    {"kanji": "起きる", "japanese": "おきる",  "romaji": "okiru", "english": "to get up, to stand up"},
    {"kanji": " 置く", "japanese": "おく",  "romaji": "oku", "english": "to put, to place"},
    {"kanji": "奥さん", "japanese": "おくさん",  "romaji": "okusan", "english": "someone’s wife"},
    {"kanji": "送る", "japanese": "おくる",  "romaji": "okuru", "english": "to send"},
    {"kanji": "お酒", "japanese": "おさけ",  "romaji": "osake", "english": "alcohol, sake"},
    {"kanji": "お皿", "japanese": "おさら",  "romaji": "osara", "english": "plate"},
    {"kanji": " 伯父さん", "japanese": "おじさん",  "romaji": "ojisan", "english": "uncle"},
    {"kanji": "おじいさん", "japanese": " おじいさん",  "romaji": "ojiisan", "english": "grand father"},
    {"kanji": "押す", "japanese": "おす",  "romaji": "osu", "english": "to push"},
    {"kanji": "遅い", "japanese": "おそい",  "romaji": "osoi", "english": "late, slow"},
    {"kanji": "お茶", "japanese": "おちゃ",  "romaji": "ocha", "english": "tea"},
    {"kanji": "お手洗い", "japanese": "おてあらい",  "romaji": "otearai", "english": "toilet, lavatory"},
    {"kanji": "お父さん", "japanese": "おとうさん",  "romaji": "otousan", "english": "father"},
    {"kanji": "弟", "japanese": "おとうと",  "romaji": "otouto", "english": "someone’s younger brother"},
    {"kanji": "男", "japanese": "おとこ",  "romaji": "otoko", "english": "man"},
    {"kanji": "男の子", "japanese": "おとこのこ",  "romaji": "otokonoko", "english": "boy"},
    {"kanji": "一昨日", "japanese": "おととい",  "romaji": "ototoi", "english": "the day before yesterday"},
    {"kanji": "一昨年", "japanese": "おととし",  "romaji": "ototoshi", "english": "the year before last"},
    {"kanji": "大人", "japanese": "おとな",  "romaji": "otona", "english": "adult"},
    {"kanji": " お腹", "japanese": "おなか",  "romaji": "onaka", "english": "stomach"},
    {"kanji": "同じ", "japanese": "おなじ",  "romaji": "onaji", "english": "same"},
    {"kanji": "お兄さん", "japanese": "おにいさん",  "romaji": "oniisan", "english": "someone’s elder brother"},
    {"kanji": "お姉さん", "japanese": "おねえさん",  "romaji": "oneesan", "english": "someone’s elder sister"},
    {"kanji": "伯母さん", "japanese": "おばさん",  "romaji": "obasan", "english": "aunt"},
    {"japanese": "おばあさん",  "romaji": "obaasan", "english": "grandmother"},
    {"kanji": "お弁当", "japanese": "おべんとう",  "romaji": "obentou", "english": "lunchbox"},
    {"kanji": "覚える", "japanese": "おぼえる",  "romaji": "oboeru", "english": "to memorize, to remember"},
    {"kanji": "重い", "japanese": "おもい",  "romaji": "omoi", "english": "heavy"},
    {"kanji": "面白い", "japanese": "おもしろい",  "romaji": "omoshiroi", "english": "interesting, funny"},
    {"kanji": "泳ぐ", "japanese": "およぐ",  "romaji": "oyogu", "english": "to swim"},
    {"kanji": "降りる", "japanese": "おりる",  "romaji": "oriru", "english": "to get off"},
    {"kanji": "終わる", "japanese": "おわる",  "romaji": "owaru", "english": "to end"},
    {"kanji": "音楽", "japanese": "おんがく",  "romaji": "ongaku", "english": "music"},
    {"kanji": "女", "japanese": "おんな",  "romaji": "onna", "english": "woman"},
    {"kanji": "女の子", "japanese": "おんなのこ",  "romaji": "onnanoko", "english": "girl"},
    {"kanji": "〜回", "japanese": "〜かい",  "romaji": "~kai", "english": "~times"},
    {"kanji": "〜階", "japanese": "〜かい",  "romaji": "~kai", "english": "~floor"},
    {"kanji": "外国", "japanese": "がいこく",  "romaji": "gaikoku", "english": "foreign country"},
    {"kanji": "外国人", "japanese": "がいこくじん",  "romaji": "gaikokujin", "english": "foreigner"},
    {"kanji": "会社", "japanese": "かいしゃ",  "romaji": "kaisha", "english": "company, enterprise"},
    {"kanji": "階段", "japanese": "かいだん",  "romaji": "kaidan", "english": "stairs"},
    {"kanji": " 買物", "japanese": "かいもの",  "romaji": "kaimono", "english": "shopping"},
    {"kanji": "買う", "japanese": "かう",  "romaji": "kau", "english": "to buy"},
    {"kanji": "返す", "japanese": "かえす",  "romaji": "kaesu", "english": "to return an object"},
    {"kanji": "帰る", "japanese": "かえる",  "romaji": "kaeru", "english": "to return home"},
    {"kanji": "顔", "japanese": "かお",  "romaji": "kao", "english": "face"},
    {"japanese": "かかる",  "romaji": "kakaru", "english": "to take time, money"},
    {"kanji": "鍵", "japanese": "かぎ",  "romaji": "kagi", "english": "key"},
    {"kanji": "書く", "japanese": "かく",  "romaji": "kaku", "english": "to write"},
    {"kanji": "学生", "japanese": "がくせい",  "romaji": "gakusei", "english": "student"},
    {"kanji": "〜か月", "japanese": "〜かげつ",  "romaji": "~kagetsu", "english": "~ number of months"},
    {"japanese": "かける",  "romaji": "kakeru", "english": "to wear"},
    {"japanese": "かける",  "romaji": "kakeru", "english": "to make a phone call"},
    {"kanji": "傘", "japanese": "かさ",  "romaji": "kasa", "english": "umbrella"},
    {"kanji": "貸す", "japanese": "かす",  "romaji": "kasu", "english": "to lend"},
    {"kanji": "風", "japanese": "かぜ",  "romaji": "kaze", "english": "wind"},
    {"kanji": "風邪", "japanese": "かぜ",  "romaji": "kaze", "english": "a cold"},
    {"kanji": "家族", "japanese": "かぞく",  "romaji": "kazoku", "english": "family"},
    {"kanji": "方", "japanese": "かた",  "romaji": "kata", "english": "person (polite)"},
    {"kanji": "片仮名", "japanese": "かたかな",  "romaji": "katakana", "english": "Katakana"},
    {"kanji": "一月", "japanese": "いちがつ",  "romaji": "ichigatsu", "english": "January"},
    {"kanji": "二月", "japanese": "にがつ",  "romaji": "nigatsu", "english": "February"},
    {"kanji": "三月", "japanese": "さんがつ",  "romaji": "sangatsu", "english": "March"},
    {"kanji": "四月", "japanese": "しがつ",  "romaji": "shigatsu", "english": "April"},
    {"kanji": "五月", "japanese": "ごがつ",  "romaji": "gogatsu", "english": "May"},
    {"kanji": "六月", "japanese": "ろくがつ",  "romaji": "rokugatsu", "english": "June"},
    {"kanji": "七月", "japanese": "しちがつ",  "romaji": "shichigatsu", "english": "July"},
    {"kanji": "八月", "japanese": "はちがつ",  "romaji": "hachigatsu", "english": "August"},
    {"kanji": "九月", "japanese": "くがつ",  "romaji": "kugatsu", "english": "September"},
    {"kanji": "十月", "japanese": "じゅうがつ",  "romaji": "juugatsu", "english": "October"},
    {"kanji": "十一月", "japanese": "じゅういちがつ",  "romaji": "juuichigatsu", "english": "November"},
    {"kanji": "十二月", "japanese": "じゅうにがつ",  "romaji": "juunigatsu", "english": "December"},
    {"kanji": "学校", "japanese": "がっこう",  "romaji": "gakkou", "english": "school"},
    {"kanji": "角", "japanese": "かど",  "romaji": "kado", "english": "corner"},
    {"kanji": "家内", "japanese": "かない",  "romaji": "kanai", "english": "my wife"},
    {"kanji": "鞄", "japanese": "かばん",  "romaji": "kaban", "english": "bag"},
    {"kanji": "花瓶", "japanese": "かびん",  "romaji": "kabin", "english": "vase"},
    {"kanji": "冠る", "japanese": "かぶる",  "romaji": "kaburu", "english": "to put on a hat"},
    {"kanji": "紙", "japanese": "かみ",  "romaji": "kami", "english": "paper"},
    {"kanji": "カメラ", "japanese": "かめら",  "romaji": "kamera", "english": "camera"},
    {"kanji": "火曜日", "japanese": "かようび",  "romaji": "kayoubi", "english": "Tuesday"},
    {"kanji": "辛い", "japanese": "からい",  "romaji": "karai", "english": "hot, spicy"},
    {"kanji": "体", "japanese": "からだ",  "romaji": "karada", "english": "body"},
    {"kanji": "借りる", "japanese": "かりる",  "romaji": "kariru", "english": "to borrow"},
    {"japanese": "〜がります",  "romaji": "~garimasu", "english": "3rd person wants to"},
    {"kanji": "軽い", "japanese": "かるい",  "romaji": "karui", "english": "light (not heavy)"},
    {"kanji": "カレンダー", "japanese": "カレンダー",  "romaji": "karendaa", "english": " calendar"},
    {"kanji": "川", "japanese": "かわ",  "romaji": "kawa", "english": "river"},
    {"kanji": " 〜側", "japanese": " ~がわ",  "romaji": "~gawa", "english": "~side"},
    {"kanji": "可愛い", "japanese": "かわいい",  "romaji": "kawaii", "english": "cute, pretty"},
    {"kanji": "漢字", "japanese": "かんじ",  "romaji": "kanji", "english": "Kanji character"},
    {"kanji": "木", "japanese": "き",  "romaji": "ki", "english": "tree"},
    {"kanji": "黄色い", "japanese": "きいろい",  "romaji": "kiiroi", "english": "yellow"},
    {"kanji": "消える", "japanese": "きえる",  "romaji": "kieru", "english": "to go out, to vanish"},
    {"kanji": "聞く", "japanese": "きく",  "romaji": "kiku", "english": "to hear, to listen, to ask"},
    {"kanji": "北", "japanese": "きた",  "romaji": "kita", "english": "north"},
    {"kanji": "ギター", "japanese": "ギター",  "romaji": "gitaa", "english": "guitar"},
    {"kanji": "汚い", "japanese": "きたない",  "romaji": "kitanai", "english": "dirty"},
    {"kanji": "喫茶店", "japanese": "きっさてん",  "romaji": "kissaten", "english": "coffee shop"},
    {"kanji": "切手", "japanese": "きって",  "romaji": "kitte", "english": "stamp"},
    {"kanji": "切符", "japanese": "きっぷ",  "romaji": "kippu", "english": "ticket"},
    {"kanji": "昨日", "japanese": "きのう",  "romaji": "kinou", "english": "yesterday"},
    {"kanji": "九", "japanese": "きゅう",  "romaji": "kyuu", "english": "nine"},
    {"kanji": "牛肉", "japanese": "ぎゅうにく",  "romaji": "gyuuniku", "english": "beef"},
    {"kanji": "牛乳", "japanese": "ぎゅうにゅう",  "romaji": "gyuunyuu", "english": "milk"},
    {"kanji": "今日", "japanese": "きょう",  "romaji": "kyou", "english": "today"},
    {"kanji": "教室", "japanese": "きょうしつ",  "romaji": "kyoushitsu", "english": "class room"},
    {"kanji": "兄弟", "japanese": "きょうだい",  "romaji": "kyoudai", "english": "siblings"},
    {"kanji": "去年", "japanese": "きょねん",  "romaji": "kyonen", "english": "last year"},
    {"kanji": "嫌い", "japanese": "きらい",  "romaji": "kirai", "english": "unpleasant, not likable"},
    {"kanji": "切る", "japanese": "きる",  "romaji": "kiru", "english": "to cut"},
    {"kanji": "着る", "japanese": "きる",  "romaji": "kiru", "english": "to wear, to put on"},
    {"kanji": "来る", "japanese": "くる",  "romaji": "kuru", "english": "to come"},
    {"japanese": "きれい",  "romaji": "kirei", "english": "beautiful, clean"},
    {"kanji": "キロ", "japanese": "キロ",  "romaji": "kiro", "english": "kg"},
    {"kanji": "キロ", "japanese": "キロ",  "romaji": "kiro", "english": "km"},
    {"kanji": "銀行", "japanese": "ぎんこう",  "romaji": "ginkou", "english": "bank"},
    {"kanji": "金曜日", "japanese": "きんようび",  "romaji": "kinyoubi", "english": "Friday"},
    {"kanji": "九", "japanese": "く",  "romaji": "ku", "english": "nine"},
    {"kanji": "薬", "japanese": "くすり",  "romaji": "kusuri", "english": "medicine"},
    {"kanji": "下さい", "japanese": "ください",  "romaji": "kudasai", "english": "give me…"},
    {"kanji": "果物", "japanese": "くだもの",  "romaji": "kudamono", "english": "fruit"},
    {"kanji": "口", "japanese": "くち",  "romaji": "kuchi", "english": "mouth"},
    {"kanji": "靴", "japanese": "くつ",  "romaji": "kutsu", "english": "shoe"},
    {"kanji": "靴下", "japanese": "くつした",  "romaji": "kutsushita", "english": "socks"},
    {"kanji": "国", "japanese": "くに",  "romaji": "kuni", "english": "country"},
    {"kanji": "曇り", "japanese": "くもり",  "romaji": "kumori", "english": "cloudy weather"},
    {"kanji": "暗い", "japanese": "くらい",  "romaji": "kurai", "english": "dark"},
    {"kanji": "ぐらい", "japanese": "ぐらい",  "romaji": "gurai", "english": "about"},
    {"kanji": "クラス", "japanese": "クラス",  "romaji": "kurasu", "english": "class"},
    {"kanji": "グラム", "japanese": "グラム",  "romaji": "guramu", "english": "gram"},
    {"kanji": "車", "japanese": "くるま",  "romaji": "kuruma", "english": "car"},
    {"kanji": "黒い", "japanese": "くろい",  "romaji": "kuroi", "english": "black"},
    {"kanji": "今朝", "japanese": "けさ",  "romaji": "kesa", "english": "this morning"},
    {"kanji": "消す", "japanese": "けす",  "romaji": "kesu", "english": "to turn off, switch off"},
    {"japanese": "けっこう",  "romaji": "kekkou", "english": "fine, all right"},
    {"kanji": "結婚", "japanese": "けっこん",  "romaji": "kekkon", "english": "marriage"},
    {"kanji": "月曜日", "japanese": "げつようび",  "romaji": "getsuyoubi", "english": "Monday"},
    {"kanji": "玄関", "japanese": "げんかん",  "romaji": "genkan", "english": "entrance of a house"},
    {"kanji": "元気", "japanese": "げんき",  "romaji": "genki", "english": "vigor, health, vitality"},
    {"kanji": "〜個", "japanese": "〜こ",  "romaji": "~ko", "english": "counter for small objects"},
    {"kanji": "五", "japanese": "ご",  "romaji": "go", "english": "five"},
    {"kanji": "〜語", "japanese": "〜ご",  "romaji": "~go", "english": "~ language"},
    {"kanji": "公園", "japanese": "こうえん",  "romaji": "kouen", "english": "park, large garden"},
    {"kanji": "交番", "japanese": "こうばん",  "romaji": "kouban", "english": "police box"},
    {"kanji": "声", "japanese": "こえ",  "romaji": "koe", "english": "voice"},
    {"kanji": "コート", "japanese": "コート",  "romaji": "kooto", "english": "coat"},
    {"kanji": "ここ", "japanese": "ここ",  "romaji": "koko", "english": "here"},
    {"kanji": "午後", "japanese": "ごご",  "romaji": "gogo", "english": "afternoon"},
    {"kanji": "九日", "japanese": "ここのか",  "romaji": "kokonoka", "english": "9th day of a month, 9 days"},
    {"kanji": "九つ", "japanese": "ここのつ",  "romaji": "kokonotsu", "english": "nine"},
    {"kanji": "ご主人", "japanese": "ごしゅじん",  "romaji": "goshujin", "english": "someone else’s husband"},
    {"kanji": "午前", "japanese": "ごぜん",  "romaji": "gozen", "english": "morning, a.m."},
    {"kanji": "答える", "japanese": "こたえる",  "romaji": "kotaeru", "english": "to answer"},
    {"kanji": "こちら", "japanese": "こちら",  "romaji": "kochira", "english": "this side, this place"},
    {"kanji": "コップ", "japanese": "コップ",  "romaji": "koppu", "english": "cup, glass"},
    {"kanji": "今年", "japanese": "ことし",  "romaji": "kotoshi", "english": "this year"},
    {"kanji": "言葉", "japanese": "ことば",  "romaji": "kotoba", "english": "phrase, language"},
    {"kanji": "子供", "japanese": "こども",  "romaji": "kodomo", "english": "child"},
    {"kanji": "この", "japanese": "この",  "romaji": "kono", "english": "this…"},
    {"kanji": "御飯", "japanese": "ごはん",  "romaji": "gohan", "english": "meal, cooked rice"},
    {"kanji": "困る", "japanese": "こまる",  "romaji": "komaru", "english": "to be in trouble"},
    {"kanji": "これ", "japanese": "これ",  "romaji": "kore", "english": "this"},
    {"kanji": "ごろ", "japanese": "ごろ",  "romaji": "goro", "english": "around…"},
    {"kanji": "今月", "japanese": "こんげつ",  "romaji": "kongetsu", "english": "this month"},
    {"kanji": "今週", "japanese": "こんしゅう",  "romaji": "konshuu", "english": "this week"},
    {"kanji": "こんな", "japanese": "こんな",  "romaji": "konna", "english": "this sort of, this kind of"},
    {"kanji": "今晩", "japanese": "こんばん",  "romaji": "konban", "english": "this evening"},
    {"kanji": "さあ", "japanese": "さあ",  "romaji": "saa", "english": "well…"},
    {"kanji": "〜歳", "japanese": "〜さい",  "romaji": "~sai", "english": "years old"},
    {"kanji": "魚", "japanese": "さかな",  "romaji": "sakana", "english": "fish"},
    {"kanji": "先", "japanese": "さき",  "romaji": "saki", "english": "earlier, former"},
    {"kanji": "咲く", "japanese": "さく",  "romaji": "saku", "english": "to blossom"},
    {"kanji": "作文", "japanese": "さくぶん",  "romaji": "sakubun", "english": "composition"},
    {"japanese": "さす",  "romaji": "sasu", "english": "to open an umbrella"},
    {"kanji": "冊", "japanese": "〜さつ",  "romaji": "~satsu", "english": "counter for books"},
    {"kanji": "雑誌", "japanese": "ざっし",  "romaji": "zasshi", "english": "magazine"},
    {"kanji": "砂糖", "japanese": "さとう",  "romaji": "satou", "english": "sugar"},
    {"kanji": "寒い", "japanese": "さむい",  "romaji": "samui", "english": "cold"},
    {"kanji": "再来年", "japanese": "さらいねん",  "romaji": "sarainen", "english": "the year after next year"},
    {"kanji": "三", "japanese": "さん",  "romaji": "san", "english": "three"},
    {"kanji": "〜さん", "japanese": "〜さん",  "romaji": "~san", "english": "Mr., Mrs."},
    {"kanji": "散歩", "japanese": "さんぽ",  "romaji": "sanpo", "english": "to take a walk"},
    {"kanji": "四", "japanese": "し",  "romaji": "shi", "english": "four"},
    {"kanji": "〜時", "japanese": "〜じ",  "romaji": "~ji", "english": "o’clock"},
    {"kanji": "塩", "japanese": "しお",  "romaji": "shio", "english": "salt"},
    {"kanji": "しかし", "japanese": "しかし",  "romaji": "shikashi", "english": "however, but"},
    {"kanji": "時間", "japanese": "じかん",  "romaji": "jikan", "english": "time"},
    {"kanji": "〜時間", "japanese": "〜じかん",  "romaji": "~jikan", "english": "~hours (classificator)"},
    {"kanji": "仕事", "japanese": "しごと",  "romaji": "shigoto", "english": "work"},
    {"kanji": "辞書", "japanese": "じしょ",  "romaji": "jisho", "english": "dictionary"},
    {"kanji": "静か", "japanese": "しずか",  "romaji": "shizuka", "english": "quiet"},
    {"kanji": "下", "japanese": "した",  "romaji": "shita", "english": "under, below"},
    {"kanji": "質問", "japanese": "しつもん",  "romaji": "shitsumon", "english": "question"},
    {"kanji": "自転車", "japanese": "じてんしゃ",  "romaji": "jitensha", "english": "bicycle"},
    {"kanji": "自動車", "japanese": "じどうしゃ",  "romaji": "jidousha", "english": "car, vehicle"},
    {"kanji": "死ぬ", "japanese": "しぬ",  "romaji": "shinu", "english": "to die, to pas away"},
    {"kanji": "字引", "japanese": "じびき",  "romaji": "jibiki", "english": "dictionary"},
    {"kanji": "自分", "japanese": "じぶん",  "romaji": "jibun", "english": "oneself"},
    {"kanji": "閉まる", "japanese": "しまる",  "romaji": "shimaru", "english": "to close"},
    {"kanji": "閉める", "japanese": "しめる",  "romaji": "shimeru", "english": "to close"},
    {"kanji": "締める", "japanese": "しめる",  "romaji": "shimeru", "english": "to fasten a seatbelt"},
    {"kanji": "じゃ", "japanese": "じゃ",  "romaji": "ja", "english": "well, then"},
    {"kanji": "写真", "japanese": "しゃしん",  "romaji": "shashin", "english": "photo"},
    {"kanji": "シャツ", "japanese": "シャツ",  "romaji": "shatsu", "english": "shirt"},
    {"kanji": "十", "japanese": "じゅう",  "romaji": "juu", "english": "ten"},
    {"kanji": "~週間", "japanese": "〜しゅうかん",  "romaji": "~shuukan", "english": "… weeks"},
    {"kanji": "授業", "japanese": "じゅぎょう",  "romaji": "jugyou", "english": "lesson, class"},
    {"kanji": "宿題", "japanese": "しゅくだい",  "romaji": "shukudai", "english": "homework"},
    {"kanji": "上手", "japanese": "じょうず",  "romaji": "jouzu", "english": "to be good at something"},
    {"kanji": "丈夫", "japanese": "じょうぶ",  "romaji": "joubu", "english": "to be strong, durable"},
    {"kanji": "醤油", "japanese": "しょうゆ",  "romaji": "shouyu", "english": "soy sauce"},
    {"kanji": "食堂", "japanese": "しょくどう",  "romaji": "shokudou", "english": "dining room, canteen"},
    {"kanji": "知る", "japanese": "しる",  "romaji": "shiru", "english": "to know"},
    {"kanji": "白い", "japanese": "しろい",  "romaji": "shiroi", "english": "white"},
    {"kanji": "〜人", "japanese": "〜じん",  "romaji": "~jin", "english": "~an, ~ese (nationality)"},
    {"kanji": "新聞", "japanese": "しんぶん",  "romaji": "shinbun", "english": "newspaper"},
    {"kanji": "水曜日", "japanese": "すいようび",  "romaji": "suiyoubi", "english": "Wednesday"},
    {"kanji": "吸う", "japanese": "すう",  "romaji": "suu", "english": "to breathe, to smoke"},
    {"kanji": "スカート", "japanese": "スカート",  "romaji": "sukaato", "english": "skirt"},
    {"kanji": "好き", "japanese": "すき",  "romaji": "suki", "english": "to like"},
    {"kanji": "〜過ぎ", "japanese": "〜すぎ",  "romaji": "~sugi", "english": "past, over"},
    {"kanji": "すぐに", "japanese": "すぐに",  "romaji": "sugu ni", "english": "at once"},
    {"kanji": "少し", "japanese": "すこし",  "romaji": "sukoshi", "english": "a little"},
    {"kanji": "涼しい", "japanese": "すずしい",  "romaji": "suzushii", "english": "cool"},
    {"kanji": "〜ずつ", "japanese": "〜ずつ",  "romaji": "~zutsu", "english": "each"},
    {"kanji": "ストーブ", "japanese": "ストーブ",  "romaji": "sutoobu", "english": "stove, heater"},
    {"kanji": "スプーン", "japanese": "スプーン",  "romaji": "supuun", "english": "spoon"},
    {"kanji": "スポーツ", "japanese": "スポーツ",  "romaji": "supootsu", "english": "sports"},
    {"kanji": "ズボン", "japanese": "ズボン",  "romaji": "zubon", "english": "trousers"},
    {"kanji": "住む", "japanese": "すむ",  "romaji": "sumu", "english": "to live, to reside somewhere"},
    {"kanji": "スリッパ", "japanese": "スリッパ",  "romaji": "surippa", "english": "slipper"},
    {"kanji": "する", "japanese": "する",  "romaji": "suru", "english": "to do"},
    {"kanji": "座る", "japanese": "すわる",  "romaji": "suwaru", "english": "to sit"},
    {"kanji": "背", "japanese": "せい",  "romaji": "sei", "english": "height"},
    {"kanji": "生徒", "japanese": "せいと",  "romaji": "seito", "english": "student"},
    {"kanji": "セーター", "japanese": "セーター",  "romaji": "seetaa", "english": "sweater"},
    {"kanji": "石鹸", "japanese": "せっけん",  "romaji": "sekken", "english": "soap"},
    {"kanji": "背広", "japanese": "せびろ",  "romaji": "sebiro", "english": "jacket, suit"},
    {"kanji": "狭い", "japanese": "せまい",  "romaji": "semai", "english": "narrow"},
    {"kanji": "ゼロ", "japanese": "ゼロ",  "romaji": "zero", "english": "zero"},
    {"kanji": "千", "japanese": "せん",  "romaji": "sen", "english": "1,000, thousand"},
    {"kanji": "先月", "japanese": "せんげつ",  "romaji": "sengetsu", "english": "last month"},
    {"kanji": "先週", "japanese": "せんしゅう",  "romaji": "senshuu", "english": "last week"},
    {"kanji": "先生", "japanese": "せんせい",  "romaji": "sensei", "english": "teacher"},
    {"kanji": "洗濯", "japanese": "せんたく",  "romaji": "sentaku", "english": "washing, to wash"},
    {"kanji": "全部", "japanese": "ぜんぶ",  "romaji": "zenbu", "english": "all"},
    {"kanji": "そう", "japanese": "そう",  "romaji": "sou", "english": "so"},
    {"kanji": "掃除", "japanese": "そうじ",  "romaji": "souji", "english": "to clean"},
    {"kanji": "そうして", "japanese": "そうして",  "romaji": "soushite", "english": "and then"},
    {"kanji": "そこ", "japanese": "そこ",  "romaji": "soko", "english": "there"},
    {"kanji": "そちら", "japanese": "そちら",  "romaji": "sochira", "english": "there (polite)"},
    {"kanji": "外", "japanese": "そと",  "romaji": "soto", "english": "outside"},
    {"kanji": "その", "japanese": "その",  "romaji": "sono", "english": "that…"},
    {"kanji": "そば", "japanese": "そば",  "romaji": "soba", "english": "next to"},
    {"kanji": "空", "japanese": "そら",  "romaji": "sora", "english": "sky"},
    {"kanji": "それ", "japanese": "それ",  "romaji": "sore", "english": "that"},
    {"kanji": "それから", "japanese": "それから",  "romaji": "sorekara", "english": "after that"},
    {"kanji": "それでは", "japanese": "それでは",  "romaji": "soredewa", "english": "then, well"},
    {"kanji": "〜台", "japanese": "〜だい",  "romaji": "~dai", "english": "counter for machines"},
    {"kanji": "大学", "japanese": "だいがく",  "romaji": "daigaku", "english": "university"},
    {"kanji": "大使館", "japanese": "たいしかん",  "romaji": "taishikan", "english": "embassy"},
    {"kanji": "大丈夫", "japanese": "だいじょうぶ",  "romaji": "daijoubu", "english": "OK"},
    {"kanji": "大好き", "japanese": "だいすき",  "romaji": "daisuki", "english": "to be very fond of"},
    {"kanji": "大切", "japanese": "たいせつ",  "romaji": "taisetsu", "english": "very important"},
    {"japanese": "たいてい",  "romaji": "taitei", "english": "mostly, usually"},
    {"kanji": "台所", "japanese": "だいどころ",  "romaji": "daidokoro", "english": "kitchen"},
    {"kanji": "大変", "japanese": "たいへん",  "romaji": "taihen", "english": "very, serious"},
    {"kanji": "高い", "japanese": "たかい",  "romaji": "takai", "english": "high, expensive"},
    {"kanji": "沢山", "japanese": "たくさん",  "romaji": "takusan", "english": "many, much"},
    {"kanji": "タクシー", "japanese": "タクシー",  "romaji": "takushii", "english": "taxi"},
    {"kanji": "出す", "japanese": "だす",  "romaji": "dasu", "english": "to take out, hand in"},
    {"kanji": "~達", "japanese": "〜たち",  "romaji": "~tachi", "english": "more than one, and others"},
    {"kanji": "立つ", "japanese": "たつ",  "romaji": "tatsu", "english": "to stand"},
    {"kanji": "建物", "japanese": "たてもの",  "romaji": "tatemono", "english": "building"},
    {"kanji": "楽しい", "japanese": "たのしい",  "romaji": "tanoshii", "english": "pleasant, enjoyable"},
    {"kanji": "頼む", "japanese": "たのむ",  "romaji": "tanomu", "english": "to ask, to request"},
    {"kanji": "たばこ", "japanese": "たばこ",  "romaji": "tabako", "english": "cigarette"},
    {"kanji": "多分", "japanese": "たぶん",  "romaji": "tabun", "english": "perhaps, probably"},
    {"kanji": "食べ物", "japanese": "たべもの",  "romaji": "tabemono", "english": "food"},
    {"kanji": "食べる", "japanese": "たべる",  "romaji": "taberu", "english": "to eat"},
    {"kanji": "卵", "japanese": "たまご",  "romaji": "tamago", "english": "egg"},
    {"kanji": "誰", "japanese": "だれ",  "romaji": "dare", "english": "who?"},
    {"kanji": "誕生日", "japanese": "たんじょうび",  "romaji": "tanjoubi", "english": "birthday"},
    {"kanji": "だんだん", "japanese": "だんだん",  "romaji": "dandan", "english": "gradually"},
    {"kanji": "小さい", "japanese": "ちいさい",  "romaji": "chiisai", "english": "small"},
    {"kanji": "近い", "japanese": "ちかい",  "romaji": "chikai", "english": "near, close"},
    {"kanji": "違う", "japanese": "ちがう",  "romaji": "chigau", "english": "different"},
    {"kanji": "地下鉄", "japanese": "ちかてつ",  "romaji": "chikatetsu", "english": "subway"},
    {"kanji": "地図", "japanese": "ちず",  "romaji": "chizu", "english": "map"},
    {"kanji": "父", "japanese": "ちち",  "romaji": "chichi", "english": "my father"},
    {"kanji": "茶色", "japanese": "ちゃいろ",  "romaji": "chairo", "english": "brown"},
    {"kanji": "茶碗", "japanese": "ちゃわん",  "romaji": "chawan", "english": "rice bowl"},
    {"kanji": "〜中", "japanese": "〜ちゅう",  "romaji": "~chuu", "english": "in the middle of"},
    {"kanji": "ちょうど", "japanese": "ちょうど",  "romaji": "choudo", "english": "just"},
    {"kanji": "ちょっと", "japanese": "ちょっと",  "romaji": "chotto", "english": "a little"},
    {"kanji": "一日", "japanese": "ついたち",  "romaji": "tsuitachi", "english": "the 1st day of a month"},
    {"kanji": "使う", "japanese": "つかう",  "romaji": "tsukau", "english": "to use"},
    {"kanji": "疲れる", "japanese": "つかれる",  "romaji": "tsukareru", "english": "to get tired"},
    {"kanji": "次", "japanese": "つぎ",  "romaji": "tsugi", "english": "next"},
    {"kanji": "着く", "japanese": "つく",  "romaji": "tsuku", "english": "to arrive"},
    {"kanji": "机", "japanese": "つくえ",  "romaji": "tsukue", "english": "table"},
    {"kanji": "作る", "japanese": "つくる",  "romaji": "tsukuru", "english": "to make, to produce"},
    {"kanji": "点ける", "japanese": "つける",  "romaji": "tsukeru", "english": "to turn on"},
    {"kanji": "勤める", "japanese": "つとめる",  "romaji": "tsutomeru", "english": "to work for someone"},
    {"kanji": "詰らない", "japanese": "つまらない",  "romaji": "tsumaranai", "english": "uninteresting"},
    {"kanji": "冷たい", "japanese": "つめたい",  "romaji": "tsumetai", "english": "cold"},
    {"kanji": "強い", "japanese": "つよい",  "romaji": "tsuyoi", "english": "strong"},
    {"kanji": "手", "japanese": "て",  "romaji": "te", "english": "hand"},
    {"kanji": "テープ", "japanese": "テープ",  "romaji": "teepu", "english": "tape"},
    {"kanji": "テープレコーダー", "japanese": "テープレコーダー",  "romaji": " teepu rekoodaa", "english": "tape recorder"},
    {"kanji": "テーブル", "japanese": "テーブル",  "romaji": "teeburu", "english": "table"},
    {"kanji": "出かける", "japanese": "でかける",  "romaji": "dekakeru", "english": "to go out"},
    {"kanji": "手紙", "japanese": "てがみ",  "romaji": "tegami", "english": "letter"},
    {"kanji": "出来る", "japanese": "できる",  "romaji": "dekiru", "english": "can"},
    {"kanji": "出口", "japanese": "でぐち",  "romaji": "deguchi", "english": "exit"},
    {"kanji": "テスト", "japanese": "テスト",  "romaji": "tesuto", "english": "test"},
    {"kanji": "では", "japanese": "では",  "romaji": "dewa", "english": "then, well"},
    {"kanji": "デパート", "japanese": "デパート",  "romaji": "depaato", "english": "department store"},
    {"kanji": "でも", "japanese": "でも",  "romaji": "demo", "english": "but"},
    {"kanji": "出ます", "japanese": "でます",  "romaji": "demasu", "english": "to leave"},
    {"kanji": "テレビ", "japanese": "テレビ",  "romaji": "terebi", "english": "TV"},
    {"kanji": "天気", "japanese": "てんき",  "romaji": "tenki", "english": "weather"},
    {"kanji": "電気", "japanese": "でんき",  "romaji": "denki", "english": "electricity"},
    {"kanji": "電車", "japanese": "でんしゃ",  "romaji": "densha", "english": "train"},
    {"kanji": "電話", "japanese": "でんわ",  "romaji": "denwa", "english": "phone"},
    {"kanji": "戸", "japanese": "と",  "romaji": "to", "english": "door"},
    {"kanji": "〜度", "japanese": "〜ど",  "romaji": "~do", "english": "~times, ~degree"},
    {"kanji": "ドア", "japanese": "ドア",  "romaji": "doa", "english": "door"},
    {"kanji": "トイレ", "japanese": "トイレ",  "romaji": "toire", "english": "toilet, lavatory"},
    {"kanji": "どう", "japanese": "どう",  "romaji": "dou", "english": "how?"},
    {"kanji": "どうして", "japanese": "どうして",  "romaji": "doushite", "english": "why?"},
    {"kanji": "どうぞ", "japanese": "どうぞ",  "romaji": "douzo", "english": "please, here you are"},
    {"kanji": "動物", "japanese": "どうぶつ",  "romaji": "doubutsu", "english": "animal"},
    {"kanji": "どうも", "japanese": "どうも",  "romaji": "doumo", "english": "thanks"},
    {"kanji": "十", "japanese": "とお",  "romaji": "too", "english": "ten"},
    {"kanji": "遠い", "japanese": "とおい",  "romaji": "tooi", "english": "far"},
    {"kanji": "十日", "japanese": "とおか",  "romaji": "tooka", "english": "the 10th day of a month, 10 days"},
    {"kanji": "時々", "japanese": "ときどき",  "romaji": "tokidoki", "english": "sometimes"},
    {"kanji": "時計", "japanese": "とけい",  "romaji": "tokei", "english": "watch, clock"},
    {"kanji": "どこ", "japanese": "どこ",  "romaji": "doko", "english": "where?"},
    {"kanji": "所", "japanese": "ところ",  "romaji": "tokoro", "english": "place"},
    {"kanji": "図書館", "japanese": "としょかん",  "romaji": "toshokan", "english": "library"},
    {"kanji": "どちら", "japanese": "どちら",  "romaji": "dochira", "english": "which, where (polite)"},
    {"kanji": "とても", "japanese": "とても",  "romaji": "totemo", "english": "very much, quiet"},
    {"kanji": "どなた", "japanese": "どなた",  "romaji": "donata", "english": "who (polite)"},
    {"kanji": "隣り", "japanese": "となり",  "romaji": "tonari", "english": "next to"},
    {"kanji": "どの", "japanese": "どの",  "romaji": "dono", "english": "which?"},
    {"kanji": "飛ぶ", "japanese": "とぶ",  "romaji": "tobu", "english": "to fly"},
    {"kanji": "止まる", "japanese": "とまる",  "romaji": "tomaru", "english": "to stop"},
    {"kanji": "友達", "japanese": "ともだち",  "romaji": "tomodachi", "english": "friend"},
    {"kanji": "土曜日", "japanese": "どようび",  "romaji": "doyoubi", "english": "Saturday"},
    {"kanji": "鳥", "japanese": "とり",  "romaji": "tori", "english": "bird"},
    {"kanji": "鶏肉", "japanese": "とりにく",  "romaji": "toriniku", "english": "chicken meat"},
    {"kanji": "取る", "japanese": "とる",  "romaji": "toru", "english": "to take"},
    {"kanji": "撮る", "japanese": "とる",  "romaji": "toru", "english": "to take a photo"},
    {"kanji": "どれ", "japanese": "どれ",  "romaji": "dore", "english": "which?"},
    {"kanji": "どんな", "japanese": "どんな",  "romaji": "donna", "english": "what kind of?"},
    {"kanji": "ナイフ", "japanese": "ナイフ",  "romaji": "naifu", "english": "knife"},
    {"kanji": "中", "japanese": "なか",  "romaji": "naka", "english": "inside"},
    {"kanji": "長い", "japanese": "ながい",  "romaji": "nagai", "english": "long"},
    {"kanji": "鳴く", "japanese": "なく",  "romaji": "naku", "english": "to sing, mew, moo"},
    {"kanji": "夏", "japanese": "なつ",  "romaji": "natsu", "english": "summer"},
    {"kanji": "夏休み", "japanese": "なつやすみ",  "romaji": "natsuyasumi", "english": "summer vacation"},
    {"kanji": "〜など", "japanese": "〜など",  "romaji": "~nado", "english": "and so on"},
    {"kanji": "七つ", "japanese": "ななつ",  "romaji": "nanatsu", "english": "seven"},
    {"kanji": "何", "japanese": "なに",  "romaji": "nani", "english": "what?"},
    {"kanji": "七日", "japanese": "なのか",  "romaji": "nanoka", "english": "the 7th of a month, 7 days"},
    {"kanji": "名前", "japanese": "なまえ",  "romaji": "namae", "english": "name"},
    {"kanji": "習う", "japanese": "ならう",  "romaji": "narau", "english": "to learn"},
    {"kanji": "並ぶ", "japanese": "ならぶ",  "romaji": "narabu", "english": "to form a line"},
    {"kanji": "並べる", "japanese": "ならべる",  "romaji": "naraberu", "english": "to line up"},
    {"japanese": "なる",  "romaji": "naru", "english": "to become"},
    {"kanji": "二", "japanese": "に",  "romaji": "ni", "english": "two"},
    {"kanji": "賑やか", "japanese": "にぎやか",  "romaji": "nigiyaka", "english": "lively"},
    {"kanji": "お肉", "japanese": "おにく",  "romaji": "oniku", "english": "meat"},
    {"kanji": "西", "japanese": "にし",  "romaji": "nishi", "english": "west"},
    {"kanji": "〜日", "japanese": "〜にち",  "romaji": "~nichi", "english": "…st, ..nd, ..th"},
    {"kanji": "日曜日", "japanese": "にちようび",  "romaji": "nichiyoubi", "english": "Sunday"},
    {"kanji": "荷物", "japanese": "にもつ",  "romaji": "nimotsu", "english": "luggage"},
    {"kanji": "ニュース", "japanese": "ニュース",  "romaji": "nyuusu", "english": "news"},
    {"kanji": "庭", "japanese": "にわ",  "romaji": "niwa", "english": "garden"},
    {"kanji": "〜人", "japanese": "~にん",  "romaji": "~nin", "english": "… people"},
    {"kanji": "脱ぐ", "japanese": "ぬぐ",  "romaji": "nugu", "english": "to take off clothes"},
    {"kanji": "ネクタイ", "japanese": "ネクタイ",  "romaji": "nekutai", "english": "necktie"},
    {"kanji": "寝る", "japanese": "ねる",  "romaji": "neru", "english": "to go to bed"},
    {"kanji": "〜年", "japanese": "〜ねん",  "romaji": "~nen", "english": "~years"},
    {"kanji": "ノート", "japanese": "ノート",  "romaji": "nooto", "english": "notebook"},
    {"kanji": "登る", "japanese": "のぼる",  "romaji": "noboru", "english": "to climb up"},
    {"kanji": "飲物", "japanese": "のみもの",  "romaji": "nomimono", "english": "drinks"},
    {"kanji": "飲む", "japanese": "のむ",  "romaji": "nomu", "english": "to drink"},
    {"kanji": "乗る", "japanese": "のる",  "romaji": "noru", "english": "to take, to ride"},
    {"kanji": "歯", "japanese": "は",  "romaji": "ha", "english": "teeth"},
    {"kanji": "パーテイー", "japanese": "パーテイー",  "romaji": "paateii", "english": "party"},
    {"kanji": "はい", "japanese": "はい",  "romaji": "hai", "english": "yes"},
    {"kanji": "〜はい", "japanese": "〜はい",  "romaji": "~hai", "english": "cups of ~"},
    {"kanji": "灰皿", "japanese": "はいざら",  "romaji": "haizara", "english": "ashtray"},
    {"kanji": "入る", "japanese": "はいる",  "romaji": "hairu", "english": "to enter"},
    {"kanji": "葉書", "japanese": "はがき",  "romaji": "hagaki", "english": "postcard"},
    {"kanji": "履く", "japanese": "はく",  "romaji": "haku", "english": "to put on shoes"},
    {"kanji": "箱", "japanese": "はこ",  "romaji": "hako", "english": "box"},
    {"kanji": "橋", "japanese": "はし",  "romaji": "hashi", "english": "bridge"},
    {"kanji": "箸", "japanese": "はし",  "romaji": "hashi", "english": "chopsticks"},
    {"kanji": "始まる", "japanese": "はじまる",  "romaji": "hajimaru", "english": "to begin, to start"},
    {"kanji": "始め", "japanese": "はじめ",  "romaji": "hajime", "english": "start, the beginning"},
    {"kanji": "初めて", "japanese": "はじめて",  "romaji": "hajimete", "english": "for the first time"},
    {"kanji": "走る", "japanese": "はしる",  "romaji": "hashiru", "english": "to run"},
    {"kanji": "バス", "japanese": "バス",  "romaji": "basu", "english": "bus"},
    {"kanji": "バター", "japanese": "バター",  "romaji": "bataa", "english": "butter"},
    {"kanji": "二十歳", "japanese": "はたち",  "romaji": "hatachi", "english": "20 years old"},
    {"kanji": "働く", "japanese": "はたらく",  "romaji": "hataraku", "english": "to work"},
    {"kanji": "八", "japanese": "はち",  "romaji": "hachi", "english": "eight"},
    {"kanji": "二十日", "japanese": "はつか",  "romaji": "hatsuka", "english": "the 20th of the month, 20 days"},
    {"kanji": "花", "japanese": "はな",  "romaji": "hana", "english": "flower"},
    {"kanji": "鼻", "japanese": "はな",  "romaji": "hana", "english": "nose"},
    {"kanji": "話", "japanese": "はなし",  "romaji": "hanashi", "english": "conversation, tale"},
    {"kanji": "話す", "japanese": "はなす",  "romaji": "hanasu", "english": "to talk, to speak, to tell"},
    {"kanji": "母", "japanese": "はは",  "romaji": "haha", "english": "my mother"},
    {"kanji": "早い", "japanese": "はやい",  "romaji": "hayai", "english": "early"},
    {"kanji": "速い", "japanese": "はやい",  "romaji": "hayai", "english": "fast, quick"},
    {"kanji": " 春", "japanese": "はる",  "romaji": "haru", "english": "spring"},
    {"kanji": "張る", "japanese": "はる",  "romaji": "haru", "english": "to put something on, to stick"},
    {"kanji": "晴れる", "japanese": "はれる",  "romaji": "hareru", "english": "to clear up"},
    {"kanji": "〜半", "japanese": "〜はん",  "romaji": "~han", "english": "Half~"},
    {"kanji": "晩", "japanese": "ばん",  "romaji": "ban", "english": "evening"},
    {"kanji": "~番", "japanese": "〜ばん",  "romaji": "~ban", "english": "No.~, ranking"},
    {"kanji": "パン", "japanese": "パン",  "romaji": "pan", "english": "bread"},
    {"kanji": "ハンカチ", "japanese": "ハンカチ",  "romaji": "hankachi", "english": "handkerchief"},
    {"kanji": "番号", "japanese": "ばんごう",  "romaji": "bangou", "english": "number"},
    {"kanji": "晩ご飯", "japanese": "ばんごはん",  "romaji": "bangohan", "english": "dinner"},
    {"kanji": "半分", "japanese": "はんぶん",  "romaji": "hanbun", "english": "half"},
    {"kanji": "東", "japanese": "ひがし",  "romaji": "higashi", "english": "east"},
    {"kanji": "〜匹", "japanese": "〜ひき",  "romaji": "~hiki", "english": "counter for animals"},
    {"kanji": "引く", "japanese": "ひく",  "romaji": "hiku", "english": "to pull"},
    {"kanji": "弾く", "japanese": "ひく",  "romaji": "hiku", "english": "to play (an instrument)"},
    {"kanji": "低い", "japanese": "ひくい",  "romaji": "hikui", "english": " low"},
    {"kanji": "飛行機", "japanese": "ひこうき",  "romaji": "hikouki", "english": "plane"},
    {"kanji": "左", "japanese": "ひだり",  "romaji": "hidari", "english": "left"},
    {"kanji": "人", "japanese": "ひと",  "romaji": "hito", "english": "person"},
    {"kanji": "一つ", "japanese": "ひとつ",  "romaji": "hitotsu", "english": "one"},
    {"kanji": "一月", "japanese": "ひとつき",  "romaji": "hitotsuki", "english": "one month"},
    {"kanji": "一人", "japanese": "ひとり",  "romaji": "hitori", "english": "one person"},
    {"kanji": "暇", "japanese": " ひま",  "romaji": "hima", "english": "free time, leisure"},
    {"kanji": "百", "japanese": "ひゃく",  "romaji": "hyaku", "english": "hundred"},
    {"kanji": "病院", "japanese": "びょういん",  "romaji": "byouin", "english": "hospital"},
    {"kanji": "病気", "japanese": "びょうき",  "romaji": "byouki", "english": "ill, sick"},
    {"kanji": " 平仮名", "japanese": "ひらがな",  "romaji": "hiragana", "english": "hiragana characters"},
    {"kanji": "昼", "japanese": "ひる",  "romaji": "hiru", "english": "noon"},
    {"kanji": "昼ご飯", "japanese": "ひるごはん",  "romaji": "hirugohan", "english": "lunch"},
    {"kanji": "広い", "japanese": "ひろい",  "romaji": "hiroi", "english": "wide, spacious"},
    {"kanji": "フィルム", "japanese": "フィルム",  "romaji": "firumu", "english": "film"},
    {"kanji": "封筒", "japanese": "ふうとう",  "romaji": "fuutou", "english": "envelope"},
    {"kanji": "プール", "japanese": "プール",  "romaji": "puuru", "english": "pool"},
    {"kanji": "フォーク", "japanese": "フォーク",  "romaji": "fooku", "english": "fork"},
    {"kanji": "吹く", "japanese": "ふく",  "romaji": "fuku", "english": "to blow (wind)"},
    {"kanji": "服", "japanese": "ふく",  "romaji": "fuku", "english": "clothes"},
    {"kanji": "二つ", "japanese": "ふたつ",  "romaji": "futatsu", "english": "two"},
    {"kanji": "豚肉", "japanese": "ぶたにく",  "romaji": "butaniku", "english": "pork"},
    {"kanji": "二人", "japanese": "ふたり",  "romaji": "futari", "english": "two people"},
    {"kanji": "二日", "japanese": "ふつか",  "romaji": "futsuka", "english": "2nd day of the month, 2 days"},
    {"kanji": "太い", "japanese": "ふとい",  "romaji": "futoi", "english": "thick, fat"},
    {"kanji": "降る", "japanese": "ふる",  "romaji": "furu", "english": "to fall (rain, snow)"},
    {"kanji": "古い", "japanese": "ふるい",  "romaji": "furui", "english": "old"},
    {"kanji": "お風呂", "japanese": "おふろ",  "romaji": "ofuro", "english": "bath"},
    {"kanji": "〜分", "japanese": "〜ふん",  "romaji": "~fun", "english": "~minutes"},
    {"kanji": "ページ", "japanese": "ページ",  "romaji": "peeji", "english": "page"},
    {"kanji": "下手", "japanese": "へた",  "romaji": "heta", "english": "not good at something"},
    {"kanji": "ベッド", "japanese": "ベッド",  "romaji": "beddo", "english": "bed"},
    {"kanji": "部屋", "japanese": "へや",  "romaji": "heya", "english": "room"},
    {"kanji": "辺", "japanese": "へん",  "romaji": "hen", "english": "side, part, area"},
    {"kanji": "ペン", "japanese": "ぺん",  "romaji": "pen", "english": "pen"},
    {"kanji": "勉強", "japanese": "べんきょう",  "romaji": "benkyou", "english": "to study"},
    {"kanji": "便利", "japanese": "べんり",  "romaji": "benri", "english": "convenient"},
    {"kanji": "方", "japanese": "ほう",  "romaji": "hou", "english": "~より〜のほうが〜"},
    {"kanji": "帽子", "japanese": "ぼうし",  "romaji": "boushi", "english": "hat"},
    {"kanji": "ボールペン", "japanese": "ボールペン",  "romaji": "boorupen", "english": "ballpen"},
    {"kanji": "他", "japanese": "ほか",  "romaji": "hoka", "english": "another, other"},
    {"kanji": "ポケット", "japanese": "ポケット",  "romaji": "poketto", "english": "pocket"},
    {"kanji": "欲しい", "japanese": "ほしい",  "romaji": "hoshii", "english": "to want something"},
    {"kanji": "細い", "japanese": "ほそい",  "romaji": "hosoi", "english": "thin, fine"},
    {"kanji": "ボタン", "japanese": "ボタン",  "romaji": "botan", "english": "button"},
    {"kanji": "ホテル", "japanese": "ホテル",  "romaji": "hoteru", "english": "hotel"},
    {"kanji": "本", "japanese": "ほん",  "romaji": "hon", "english": "book"},
    {"kanji": "〜本", "japanese": "~ほん",  "romaji": "~hon", "english": "counter for long objects"},
    {"kanji": "本棚", "japanese": "ほんだな",  "romaji": "hondana", "english": "bookshelf"},
    {"kanji": "本当に", "japanese": "ほんとうに",  "romaji": "hontouni", "english": "really"},
    {"kanji": "〜枚", "japanese": "〜まい",  "romaji": "~mai", "english": "counter for thin objects"},
    {"kanji": "毎朝", "japanese": "まいあさ",  "romaji": "maiasa", "english": "every morning"},
    {"kanji": "毎月", "japanese": "まいつき/まいげつ",  "romaji": "maitsuki/maigetsu", "english": "every month"},
    {"kanji": "毎週", "japanese": "まいしゅう",  "romaji": "maishuu", "english": "every week"},
    {"kanji": "毎日", "japanese": "まいにち",  "romaji": "mainichi", "english": "every day"},
    {"kanji": "毎年", "japanese": "まいとし/まいねん",  "romaji": "maitoshi/mainen", "english": "every year"},
    {"kanji": "毎晩", "japanese": "まいばん",  "romaji": "maiban", "english": "every evening"},
    {"kanji": "前", "japanese": "まえ",  "romaji": "mae", "english": "front"},
    {"kanji": "〜前", "japanese": "〜まえ",  "romaji": "~mae", "english": "before, in front of"},
    {"kanji": "曲がる", "japanese": "まがる",  "romaji": "magaru", "english": "to turn"},
    {"kanji": "不味い", "japanese": "まずい",  "romaji": "mazui", "english": "bad tasting"},
    {"kanji": "また", "japanese": "また",  "romaji": "mata", "english": "also, again"},
    {"kanji": "まだ", "japanese": "まだ",  "romaji": "mada", "english": "not yet"},
    {"kanji": "町", "japanese": "まち",  "romaji": "machi", "english": "city, town"},
    {"kanji": "待つ", "japanese": "まつ",  "romaji": "matsu", "english": "to wait"},
    {"kanji": "真直ぐに", "japanese": "まっすぐに",  "romaji": "massugu ni", "english": "straight ahead"},
    {"kanji": "マッチ", "japanese": "マッチ",  "romaji": "machi", "english": "matches"},
    {"kanji": "窓", "japanese": "まど",  "romaji": "mado", "english": "window"},
    {"kanji": "丸い", "japanese": "まるい",  "romaji": "marui", "english": "round"},
    {"kanji": "万", "japanese": "まん",  "romaji": "man", "english": "ten thousand"},
    {"kanji": "万年筆", "japanese": "まんねんひつ",  "romaji": "mannenhitsu", "english": "fountain pen"},
    {"kanji": "磨く", "japanese": "みがく",  "romaji": "migaku", "english": "to polish, to brush"},
    {"kanji": "右", "japanese": "みぎ",  "romaji": "migi", "english": "right"},
    {"kanji": "短い", "japanese": "みじかい",  "romaji": "mijikai", "english": "short"},
    {"kanji": "お水", "japanese": "おみず",  "romaji": "omizu", "english": "water"},
    {"kanji": "店", "japanese": "みせ",  "romaji": "mise", "english": "shop"},
    {"kanji": "見せる", "japanese": "みせる",  "romaji": "miseru", "english": "to look, to watch"},
    {"kanji": "道", "japanese": "みち",  "romaji": "michi", "english": "road"},
    {"kanji": "三日", "japanese": "みっか",  "romaji": "mikka", "english": "3rd day of a month, 3 days"},
    {"kanji": "三つ", "japanese": "みっつ",  "romaji": "mittsu", "english": "three"},
    {"kanji": "皆さん", "japanese": "みなさん",  "romaji": "minsan", "english": "everyone"},
    {"kanji": "南", "japanese": "みなみ",  "romaji": "minami", "english": "south"},
    {"kanji": "耳", "japanese": "みみ",  "romaji": "mimi", "english": "ear"},
    {"kanji": "見る", "japanese": "みる",  "romaji": "miru", "english": "to see, to watch"},
    {"kanji": "皆", "japanese": "みんな",  "romaji": "minna", "english": "all, everyone"},
    {"kanji": "六日", "japanese": "むいか",  "romaji": "muika", "english": "the 6th day of a month, 6 days"},
    {"kanji": "向こう", "japanese": "むこう",  "romaji": "mukou", "english": "over there"},
    {"kanji": "難しい", "japanese": "むずかしい",  "romaji": "muzukashii", "english": "difficult"},
    {"kanji": "六つ", "japanese": "むっつ",  "romaji": "muttsu", "english": "six"},
    {"kanji": "目", "japanese": "め",  "romaji": "me", "english": "eye"},
    {"kanji": "メートル", "japanese": "メートル",  "romaji": "meetoru", "english": "meter"},
    {"kanji": "めがね", "japanese": "めがね",  "romaji": "megane", "english": "a pair of glasses"},
    {"kanji": "もう", "japanese": "もう",  "romaji": "mou", "english": "already, yet"},
    {"kanji": "もう", "japanese": "もう",  "romaji": "mou", "english": "(one) more"},
    {"kanji": "木曜日", "japanese": "もくようび",  "romaji": "mokuyoubi", "english": "Thursday"},
    {"kanji": "もしもし", "japanese": "もしもし",  "romaji": "moshimoshi", "english": "hello on the phone"},
    {"kanji": "勿論", "japanese": "もちろん",  "romaji": "mochiron", "english": "of course"},
    {"kanji": "持つ", "japanese": "もつ",  "romaji": "motsu", "english": "to have, to own"},
    {"kanji": "もっと", "japanese": "もっと",  "romaji": "motto", "english": "more"},
    {"kanji": "物", "japanese": "もの",  "romaji": "mono", "english": "thing"},
    {"kanji": "門", "japanese": "もん",  "romaji": "mon", "english": "gate"},
    {"kanji": "問題", "japanese": "もんだい",  "romaji": "mondai", "english": "problem, question"},
    {"kanji": "〜屋", "japanese": "〜や",  "romaji": "~ya", "english": "shop. store"},
    {"kanji": "八百屋", "japanese": "やおや",  "romaji": "yaoya", "english": "vegetable shop"},
    {"kanji": "野菜", "japanese": "やさい",  "romaji": "yasai", "english": "vegetable"},
    {"kanji": "優しい", "japanese": "やさしい",  "romaji": "yasashii", "english": "gentle"},
    {"kanji": "安い", "japanese": "やすい",  "romaji": "yasui", "english": "cheap, inexpensive"},
    {"kanji": "休み", "japanese": "やすみ",  "romaji": "yasumi", "english": "holiday, vacation"},
    {"kanji": "休む", "japanese": "やすむ",  "romaji": "yasumu", "english": "to rest"},
    {"kanji": "八つ", "japanese": "やっつ",  "romaji": "yattsu", "english": "eight"},
    {"kanji": "山", "japanese": "やま",  "romaji": "yama", "english": "mountain"},
    {"japanese": "やる",  "romaji": "yaru", "english": "to do"},
    {"kanji": "八日", "japanese": "ようか",  "romaji": "youka", "english": "8th day of the month, 8 days"},
    {"kanji": "洋服", "japanese": "ようふく",  "romaji": "youfuku", "english": "western style clothing"},
    {"kanji": "よく", "japanese": "よく",  "romaji": "yoku", "english": "often"},
    {"kanji": "横", "japanese": "よこ",  "romaji": "yoko", "english": "horizontal"},
    {"kanji": "四日", "japanese": "よっか",  "romaji": "yokka", "english": "4th day of the month, 4 days"},
    {"kanji": "四つ", "japanese": "よっつ",  "romaji": "yottsu", "english": "four"},
    {"kanji": "呼ぶ", "japanese": "よぶ",  "romaji": "yobu", "english": "to call"},
    {"kanji": "読む", "japanese": "よむ",  "romaji": "yomu", "english": "to read"},
    {"kanji": "夜", "japanese": "よる",  "romaji": "yoru", "english": "night"},
    {"kanji": "来月", "japanese": "らいげつ",  "romaji": "raigetsu", "english": "next month"},
    {"kanji": "来週", "japanese": "らいしゅう",  "romaji": "raishuu", "english": "next week"},
    {"kanji": "来年", "japanese": "らいねん",  "romaji": "rainen", "english": "next year"},
    {"kanji": "ラジオ", "japanese": "ラジオ",  "romaji": "rajio", "english": "radio"},
    {"kanji": "立派", "japanese": "りっぱ",  "romaji": "rippa", "english": "splendid"},
    {"kanji": "留学生", "japanese": "りゅうがくせい",  "romaji": "ryuugakusei", "english": "foreign student"},
    {"kanji": "両親", "japanese": "りょうしん",  "romaji": "ryoushin", "english": "parents"},
    {"kanji": "料理", "japanese": "りょうり",  "romaji": "ryouri", "english": "cooking"},
    {"kanji": "旅行", "japanese": "りょこう",  "romaji": "ryokou", "english": "travel"},
    {"japanese": "れい",  "romaji": "rei", "english": "zero"},
    {"kanji": "冷蔵庫", "japanese": "れいぞうこ",  "romaji": "reizouko", "english": "refrigerator"},
    {"kanji": "レコード", "japanese": "レコード",  "romaji": "rekoodo", "english": "record"},
    {"kanji": "レストラン", "japanese": "レストラン",  "romaji": "resutoran", "english": "restaurant"},
    {"kanji": "練習", "japanese": "れんしゅう",  "romaji": "renshuu", "english": "practice"},
    {"kanji": "六", "japanese": "ろく",  "romaji": "roku", "english": "six"},
    {"kanji": "ワイシャツ", "japanese": "ワイシャツ",  "romaji": "waishatsu", "english": "white shirt"},
    {"kanji": "若い", "japanese": "わかい",  "romaji": "wakai", "english": "young"},
    {"kanji": "分かる", "japanese": "わかる",  "romaji": "wakaru", "english": "to know, to understand"},
    {"kanji": "忘れる", "japanese": "わすれる",  "romaji": "wasureru", "english": "to forget"},
    {"kanji": "私", "japanese": "わたし",  "romaji": "watashi", "english": "me, I"},
    {"kanji": "渡す", "japanese": "わたす",  "romaji": "watasu", "english": "to hand over"},
    {"kanji": "渡る", "japanese": "わたる",  "romaji": "wataru", "english": "to cross"},
    {"kanji": "悪い", "japanese": "わるい",  "romaji": "warui", "english": "ba"}  
    ];